# 7-1

It discribes hows your array looks like. First element is the number of rows, second element is the number of columns.

# 7-2


In [2]:
import numpy as np

ppm = np.array([[20.80, 20.71, 21.72, 18.81],
                [19.91, 18.42, 20.73, 20.32],
                [17.32, 21.74, 23.19, 19.98]])

np.shape(ppm)

(3, 4)

# 7-3

In [6]:
np.zeros((3,2), dtype='int')

array([[0, 0],
       [0, 0],
       [0, 0]])

# 7-4

In [19]:
nums = np.linspace(1,8,8)
factors = np.reshape(nums,(2,4))
factors

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

# 7-5

In [17]:
7*np.ones((3,5), dtype='int')

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

# 7-6

In [20]:
# 1
value = factors[1,2]

#2
first_row = factors[0,:]

#3
subset = factors[:,1:3]

#4
factors[0,0:3] = factors[1,1:]

# 7-7

In [22]:
ppb = ppm*1000
ppb

array([[20800., 20710., 21720., 18810.],
       [19910., 18420., 20730., 20320.],
       [17320., 21740., 23190., 19980.]])

# 7-8 

In [26]:
data1 = np.random.rand(3,5)
data2 = np.random.rand(3,5)

avg_between_both = (data1+data2)/2
avg_between_both

array([[0.44859207, 0.46777838, 0.92918336, 0.36323569, 0.32304264],
       [0.31391206, 0.50190538, 0.49535179, 0.31793112, 0.70898523],
       [0.67713916, 0.26931878, 0.41696908, 0.50738217, 0.63780926]])

# 7-9

In [28]:
data3 = np.random.rand(3,5)
data3

array([[0.23812152, 0.08001145, 0.83962176, 0.61982349, 0.95028356],
       [0.08508011, 0.87307514, 0.27953458, 0.30292454, 0.80834799],
       [0.31201757, 0.66256985, 0.40140059, 0.19532345, 0.29174166]])

In [29]:
max_data3 = np.max(data3)
max_data3

0.9502835597917367